import React from 'react';
import { DailySummary } from '../types';
import { Share2, Calendar, CheckCircle2, Sparkles, Zap } from 'lucide-react';

interface DailyBriefProps {
  summary: DailySummary | null;
  isLoading: boolean;
  onGenerate: () => void;
}

const DailyBrief: React.FC<DailyBriefProps> = ({ summary, isLoading, onGenerate }) => {
  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-96 text-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-cyan-500 mb-4 shadow-[0_0_15px_rgba(6,182,212,0.5)]"></div>
        <h3 className="text-lg font-semibold text-slate-200">AI Intelligence Processing...</h3>
        <p className="text-slate-400 max-w-md mt-2">Synthesizing global vectors, identifying narrative arcs, and compiling your brief.</p>
      </div>
    );
  }

  if (!summary) {
    return (
      <div className="flex flex-col items-center justify-center h-96 text-center glass-panel rounded-xl p-8">
        <div className="w-20 h-20 bg-gradient-to-br from-cyan-500/20 to-blue-500/20 rounded-full flex items-center justify-center mb-6 shadow-[0_0_20px_rgba(6,182,212,0.2)]">
          <Sparkles className="w-10 h-10 text-cyan-400" />
        </div>
        <h2 className="text-2xl font-bold text-white mb-2">Ready to Brief?</h2>
        <p className="text-slate-400 max-w-md mb-8">
          Generate your personalized daily summary using Gemini 2.5. It scans all collected feeds and extracts critical signals from the noise.
        </p>
        <button 
          onClick={onGenerate}
          className="px-8 py-3 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white rounded-lg font-bold shadow-lg shadow-cyan-500/20 transition transform hover:-translate-y-0.5 border border-white/10"
        >
          Generate AI Briefing
        </button>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto">
      <div className="glass-panel rounded-xl overflow-hidden shadow-2xl">
        {/* Header */}
        <div className="bg-gradient-to-r from-slate-900 to-indigo-950 p-8 text-white relative overflow-hidden border-b border-white/10">
          <div className="absolute top-0 right-0 p-8 opacity-20">
            <Sparkles className="w-32 h-32 text-cyan-500 blur-xl" />
          </div>
          <div className="relative z-10">
            <div className="flex items-center space-x-2 text-cyan-400 mb-4 text-sm uppercase tracking-wide font-bold">
              <Calendar className="w-4 h-4" />
              <span>{summary.date} • INTELLIGENCE DIGEST</span>
            </div>
            <h1 className="text-3xl md:text-4xl font-bold leading-tight mb-2 text-transparent bg-clip-text bg-gradient-to-r from-white to-slate-300">
              {summary.headline}
            </h1>
          </div>
        </div>

        {/* Content */}
        <div className="p-8">
          {/* Takeaways */}
          <div className="bg-white/5 rounded-xl p-6 mb-8 border border-white/5">
            <h3 className="text-cyan-300 font-bold mb-4 flex items-center uppercase tracking-wider text-xs">
              <Zap className="w-4 h-4 mr-2" /> Key Takeaways
            </h3>
            <ul className="space-y-3">
              {summary.keyTakeaways.map((point, idx) => (
                <li key={idx} className="flex items-start text-slate-300">
                  <CheckCircle2 className="w-5 h-5 text-emerald-500 mr-3 flex-shrink-0 mt-0.5 drop-shadow-[0_0_3px_rgba(16,185,129,0.5)]" />
                  <span>{point}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Body */}
          <div className="prose prose-invert max-w-none text-slate-300 leading-relaxed mb-8 whitespace-pre-line">
            {summary.bodyContent}
          </div>

          {/* Trending */}
          <div className="border-t border-white/10 pt-6">
            <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3">Trending Signals</h4>
            <div className="flex flex-wrap gap-2">
              {summary.trendingTopics.map((tag, idx) => (
                <span key={idx} className="px-3 py-1 bg-white/5 text-slate-400 rounded-full text-sm hover:bg-white/10 transition cursor-default border border-white/5">
                  #{tag}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="bg-black/20 px-8 py-4 border-t border-white/5 flex justify-between items-center">
          <span className="text-xs text-slate-600 font-mono">GENERATED BY GEMINI 2.5</span>
          <div className="flex space-x-3">
            <button className="flex items-center space-x-2 text-slate-400 hover:text-white text-sm font-medium transition">
              <Share2 className="w-4 h-4" />
              <span>Share Report</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DailyBrief;